### PR TITLE
rating dup check

### PR DESCRIPTION
**Pull request by tomxhu**

### CODE REVIEW

**Comment by alexjohnson505** [comment]
Wouldn't this allow a user to only create a single rating? It's checking for duplicate UserIDs, while it should be checking for duplicate UserIDs & Book isbn13.

**Comment by tomxhu** [comment]
oh. you're right. sorry im really tired

**Comment by alexjohnson505** [comment]
Ha ha. Thanks for putting this PR up so late at night!

**Comment by alexjohnson505** [comment]
Awesome!!! :+1:

**Comment by pragsanshi** [comment]
Works like a charm, merging!

**Pull request merged**
